// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// loads
NumericVector loads(NumericVector feet, double m1, double base_ft, double base_press, double SF);
RcppExport SEXP _CraneLoads_loads(SEXP feetSEXP, SEXP m1SEXP, SEXP base_ftSEXP, SEXP base_pressSEXP, SEXP SFSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type feet(feetSEXP);
    Rcpp::traits::input_parameter< double >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< double >::type base_ft(base_ftSEXP);
    Rcpp::traits::input_parameter< double >::type base_press(base_pressSEXP);
    Rcpp::traits::input_parameter< double >::type SF(SFSEXP);
    rcpp_result_gen = Rcpp::wrap(loads(feet, m1, base_ft, base_press, SF));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CraneLoads_loads", (DL_FUNC) &_CraneLoads_loads, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_CraneLoads(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
