# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loads <- function(feet, m1, base_ft, base_press, SF) {
    .Call(`_CraneLoads_loads`, feet, m1, base_ft, base_press, SF)
}

